# Change these first
owner: filiptronicek # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: trnck.dev
    url: https://trnck.dev
  - name: Interclip
    url: https://interclip.app
  - name: Blog
    url: https://blog.trnck.dev
  - name: Status page
    url: https://status.trnck.dev
  - name: CountDowner
    url: https://countdowner.now.sh
  - name: Universal File Proxy
    url: https://external.trnck.dev/?url=https://www.electronicbeats.net/app/uploads/2016/06/rickastley.jpg
  - name: Time API
    url: https://trnck.dev/time

assignees:
  - filiptronicek

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.trnck.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://trnck.dev/assets/img/logo.png
  name: Uptime of my stuff
  introTitle: "Is stuff up or down? Who knows"
  introMessage: "Check the status of my stuff with this page."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
